
#配置静态资源前后缀
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/laji?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8080
  ssl:
    key-store: classpath:www.52mingliang.cn.jks
    key-store-password: 9652799zaq
    key-store-type: JKS
#    key-alias: www.52mingliang.cn.jks

# pageHelper配置
# 指定数据库
pagehelper:
  helper-dialect: mysql
  # 页码<=0 查询第一页，页码>=总页数查询最后一页
  reasonable: true
  # 支持通过 Mapper 接口参数来传递分页参数
  support-methods-arguments: true

